
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressWarnings(suppressMessages(library(dplyr, quietly = TRUE)))
```

## RFM Analysis

```{r rfm}
rfm_result
```

## Heat Map

```{r heatmap, fig.align='center', fig.width=6, fig.height=5}
rfm_heatmap(rfm_result)
```

## Bar Chart

```{r barchart, fig.align='center', fig.width=6, fig.height=5}
rfm_bar_chart(rfm_result)
```

## Histogram

```{r rfmhist, fig.align='center', fig.width=6, fig.height=5}
rfm_histograms(rfm_result)
```

## Customers by Orders

```{r rfmorders, fig.align='center', fig.width=6, fig.height=5}
rfm_order_dist(rfm_result)
```

## Scatter Plots

#### Recency vs Monetary Value

```{r mr, fig.align='center', fig.width=6, fig.height=6}
rfm_rm_plot(rfm_result)
```

#### Frequency vs Monetary Value

```{r fm, fig.align='center', fig.width=6, fig.height=6}
rfm_fm_plot(rfm_result)
```

#### Recency vs Frequency 

```{r fr, fig.align='center', fig.width=6, fig.height=6}
rfm_rf_plot(rfm_result)
```

## Segmentation

```{r segment}
segment_names <- c("Champions", "Loyal Customers", "Potential Loyalist",
  "New Customers", "Promising", "Need Attention", "About To Sleep",
  "At Risk", "Can't Lose Them", "Lost")

recency_lower <- c(4, 2, 3, 4, 3, 2, 2, 1, 1, 1)
recency_upper <- c(5, 5, 5, 5, 4, 3, 3, 2, 1, 2)
frequency_lower <- c(4, 3, 1, 1, 1, 2, 1, 2, 4, 1)
frequency_upper <- c(5, 5, 3, 1, 1, 3, 2, 5, 5, 2)
monetary_lower <- c(4, 3, 1, 1, 1, 2, 1, 2, 4, 1)
monetary_upper <- c(5, 5, 3, 1, 1, 3, 2, 5, 5, 2)

segments <- rfm_segment(rfm_result, segment_names, recency_lower, recency_upper,
frequency_lower, frequency_upper, monetary_lower, monetary_upper)
segments
```

## Median Recency

```{r mrecency, fig.align='center', fig.width=6, fig.height=5}
rfm_plot_median_recency(segments)
```

## Median Frequency

```{r mfrequency, fig.align='center', fig.width=6, fig.height=5}
rfm_plot_median_frequency(segments)
```

## Median Monetary Value

```{r mmonetary, fig.align='center', fig.width=6, fig.height=5}
rfm_plot_median_monetary(segments)
```